clone_depth:
environment:
  nodejs_version: "10"
  access_token:
    secure: YJGN4kn7 + Ee4G5KAw2KKVL2xPZtD0DuSg0Ay1ZIzSHJ7ALdc767qpnyNDKZIw1NP
install:
 # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm install
  - node --version
  - npm --version
  - npm install
  - npm install hexo-cli -g

build_script:
  - hexo generate

artifacts:
  - path: public
on_success:
- provider: GitHub
  - git clone
GitHub Repository: https://github.com/nvdacn/nvdacn.github.io