clone_depth: 5
environment:
  nodejs_version: "10"
  access_token:
    secure: DO1FA80B0MgslEfR6NntOIORHAtFOrzO70MvNfZK3OIHpXrundrrSBSx+nEkgx9m

install:
 # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm install
  - node --version
  - npm --version
  - npm install
  - npm install hexo-cli -g

build_script:
  - hexo generate

artifacts:
  - path: public
on_success:
   - git push https://github.com/nvdacn/nvdacn.github.io
   - hexo clean